"""revisions lol

Revision ID: a9e4ac68ceb0
Revises: a1f42a4f5b16
Create Date: 2026-04-02 17:19:54.097445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e4ac68ceb0'
down_revision: Union[str, Sequence[str], None] = 'a1f42a4f5b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('election_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('cabinet', 'club'), nullable=False),
    sa.Column('status', sa.Enum('ongoing', 'closed'), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('election_id')
    )
    op.create_table('parties',
    sa.Column('party_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('party_id')
    )
    op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.election_id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('party_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('vote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.election_id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('party_members')
    op.drop_table('candidates')
    op.drop_table('parties')
    op.drop_table('elections')
    # ### end Alembic commands ###
