"""empty message

Revision ID: dc518c347b89
Revises: 7f71ce45889d
Create Date: 2026-05-08 16:29:29.249613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc518c347b89'
down_revision: Union[str, Sequence[str], None] = '7f71ce45889d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fines', 'reason',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fines', 'reason',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
